spring:
    datasource:
        hikari:
            driver-class-name: org.mariadb.jdbc.Driver
            jdbc-url: jdbc:mariadb://localhost:3306/allra_market
            username: root
            password: q1w2e3r4!!
            pool-name: SpringBoot-3.4.2
